### ISSUE TITLE
Calibration screen not covering whole screen

### ISSUE THREAD

**Issue by JosephSummerhays1** [reinderien/xcalibrate#10]
When I run this utility, the calibration screen is showing up in the top left corner of the screen, probably one eighth the total width and height. Because of this I couldn't get a good calibration.

**Comment by reinderien** [comment]
That's weird. Given how simple the window setup is:
    
    root.attributes('-fullscreen', True)

I doubt that this application is the only one that would have troubles on your screen setup.

**Comment by JosephSummerhays1** [comment]
Indeed. I tried to run `python3 -m tkinter` and it also showed up in an incredibly small window.

**Comment by JosephSummerhays1** [comment]
Also interesting, I thought that given the window size, the calibration matrix would try to scale everything towards the top left corner. but the calibration matrix given in the terminal was almost the identity matrix. So at least it's consistent with it's scale.
`
New calibration:
[[ 1.01751036  0.         -0.01544933]
 [ 0.          0.93664713  0.05710974]
 [ 0.          0.          1.        ]]
Quality (should be at least 3): 2.4
`

I don't know anything about tkinter so I won't be that much of a help, but if I figure anything out, maybe I'll submit a PR.

**Comment by reinderien** [comment]
Sure! If you figure out a PR that succeeds in a workaround I'll look it over. In the meantime, though, this seems to me like an upstream bug - consider filing it at https://bugs.python.org/issue .
