### ISSUE TITLE
Please rename the executables due to conflict

### ISSUE THREAD

**Issue by mirabilos** [reinderien/xcalibrate#5]
Hi,

for packaging your software for Debian, please rename it due to a conflict with [xcal](https://packages.debian.org/sid/xcal). Thanks!

**Comment by reinderien** [comment]
Can't part of packaging be to alias this thing under another name?

**Comment by mirabilos** [comment]
Greg Toombs dixit:

>Can't part of packaging be to alias this thing under another name?

Sure, but your users will not be likely to find this then.

bye,
//mirabilos
-- 
„Cool, /usr/share/doc/mksh/examples/uhr.gz ist ja ein Grund,
mksh auf jedem System zu installieren.“
	-- XTaran auf der OpenRheinRuhr, ganz begeistert
(EN: “[…]uhr.gz is a reason to install mksh on every system.”)

**Comment by steinymity** [comment]
I am very interested in having xcal packaged for Debian, too. What about just calling it "xcalibrate"?

**Comment by mirabilos** [comment]
Maximilian Stein dixit:

>I am very interested in having xcal packaged for Debian, too. What
>about just calling it "xcalibrate"?

AFAICT, that name is currently free.

**Comment by reinderien** [comment]
All done. Looking forward to seeing this packaged.
